id = 'a1_bbs_mkpprocess_a1_04_020'
resourceType = 'bbs_profile'
category = 'process'
machineId = 'A1'
fileName = 'MKPProcess A1 0.4 0.20.json'
relativePath = 'presets/bbs/Process/0.4mm/MKPProcess A1 0.4 0.20.json'
